version: '3.4'

services:
  redis:
    image: redis
    ports:
      - "6379:6379"

  master-project-in-layered-architecture-generic-repository:
    build:
      context: . # This points to the root directory where the Dockerfile is located
      dockerfile: Dockerfile
    image: masterprojectinlayeredarchitecturegenericrepository
    ports:
      - "8080:80" # Map the container port 80 to host port 8080
    depends_on:
      - redis
